// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	RPCMessage
	Head
	Body
	ResponseCode
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RPCMessage struct {
	Head             *Head  `protobuf:"bytes,1,req,name=head" json:"head,omitempty"`
	Body             *Body  `protobuf:"bytes,2,req,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RPCMessage) Reset()                    { *m = RPCMessage{} }
func (m *RPCMessage) String() string            { return proto.CompactTextString(m) }
func (*RPCMessage) ProtoMessage()               {}
func (*RPCMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RPCMessage) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *RPCMessage) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type Head struct {
	SessionNo        *string `protobuf:"bytes,1,req,name=session_no" json:"session_no,omitempty"`
	MessageType      *int32  `protobuf:"varint,2,req,name=message_type" json:"message_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Head) Reset()                    { *m = Head{} }
func (m *Head) String() string            { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()               {}
func (*Head) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Head) GetSessionNo() string {
	if m != nil && m.SessionNo != nil {
		return *m.SessionNo
	}
	return ""
}

func (m *Head) GetMessageType() int32 {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return 0
}

type Body struct {
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
}

func (m *Body) Reset()                    { *m = Body{} }
func (m *Body) String() string            { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()               {}
func (*Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

var extRange_Body = []proto.ExtensionRange{
	{1000, 536870911},
}

func (*Body) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Body
}

type ResponseCode struct {
	Retcode          *int32  `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	ErrorMessgae     *string `protobuf:"bytes,2,opt,name=error_messgae" json:"error_messgae,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponseCode) Reset()                    { *m = ResponseCode{} }
func (m *ResponseCode) String() string            { return proto.CompactTextString(m) }
func (*ResponseCode) ProtoMessage()               {}
func (*ResponseCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResponseCode) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *ResponseCode) GetErrorMessgae() string {
	if m != nil && m.ErrorMessgae != nil {
		return *m.ErrorMessgae
	}
	return ""
}

func init() {
	proto.RegisterType((*RPCMessage)(nil), "rpc.RPCMessage")
	proto.RegisterType((*Head)(nil), "rpc.Head")
	proto.RegisterType((*Body)(nil), "rpc.Body")
	proto.RegisterType((*ResponseCode)(nil), "rpc.ResponseCode")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcc, 0xb1, 0xae, 0x82, 0x30,
	0x14, 0xc6, 0xf1, 0xc0, 0x85, 0x70, 0x7b, 0x2e, 0x37, 0x6a, 0xa3, 0x91, 0xd1, 0x74, 0x22, 0x0e,
	0xc4, 0x38, 0x38, 0x3a, 0xc8, 0xe2, 0x62, 0x62, 0x78, 0x01, 0x52, 0xe9, 0x09, 0x3a, 0xc8, 0x69,
	0x5a, 0x16, 0xb6, 0x3e, 0xae, 0x8f, 0x61, 0x5a, 0x17, 0xe7, 0xef, 0xfb, 0xff, 0x80, 0x19, 0xdd,
	0x55, 0xda, 0xd0, 0x48, 0xfc, 0xc7, 0xe8, 0x4e, 0x1c, 0x01, 0x9a, 0x6b, 0x7d, 0x41, 0x6b, 0x65,
	0x8f, 0x7c, 0x0d, 0xc9, 0x1d, 0xa5, 0x2a, 0xa2, 0x4d, 0x5c, 0xfe, 0xed, 0x59, 0xe5, 0xcf, 0x67,
	0x94, 0xca, 0x0f, 0x37, 0x52, 0x53, 0x11, 0x7f, 0x0d, 0x27, 0x52, 0x93, 0xd8, 0x41, 0x12, 0x0e,
	0x1c, 0xc0, 0xa2, 0xb5, 0x0f, 0x1a, 0xda, 0x81, 0x42, 0xcf, 0xf8, 0x12, 0xf2, 0xe7, 0x07, 0x6e,
	0xc7, 0x49, 0x63, 0x88, 0x53, 0xb1, 0x80, 0xc4, 0x97, 0x5b, 0xf6, 0xfb, 0xca, 0xe6, 0xce, 0x39,
	0x17, 0x8b, 0x03, 0xe4, 0x0d, 0x5a, 0x4d, 0x83, 0xc5, 0x9a, 0x14, 0xf2, 0x19, 0x64, 0x06, 0xc7,
	0x8e, 0x14, 0x06, 0x29, 0xe5, 0x2b, 0xf8, 0x47, 0x63, 0xc8, 0xb4, 0xde, 0xeb, 0xa5, 0xa7, 0xa2,
	0x92, 0xbd, 0x03, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xe0, 0x4d, 0x27, 0xcd, 0x00, 0x00, 0x00,
}
