// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

/*
Package rpc_account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	Account
	CreateAccountRequest
	CreateAccountResponse
	DeleteAccountRequest
	DeleteAccountResponse
	GetAccountInfoRequest
	GetAccountInfoResponse
	SetAccountNameRequest
	SetAccountNameResponse
	SetAccountPasswdRequest
	SetAccountPasswdResponse
*/
package rpc_account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import rpc "pbtest/proto/rpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_CREATE_ACCOUNT_REQUEST      MessageType = 1001
	MessageType_CREATE_ACCOUNT_RESPONSE     MessageType = 1002
	MessageType_DELETE_ACCOUNT_REQUEST      MessageType = 1003
	MessageType_DELETE_ACCOUNT_RESPONSE     MessageType = 1004
	MessageType_GET_ACCOUNT_INFO_REQUEST    MessageType = 1005
	MessageType_GET_ACCOUNT_INFO_RESPONSE   MessageType = 1006
	MessageType_SET_ACCOUNT_NAME_REQUEST    MessageType = 1007
	MessageType_SET_ACCOUNT_NAME_RESPONSE   MessageType = 1008
	MessageType_SET_ACCOUNT_PASSWD_REQUEST  MessageType = 1009
	MessageType_SET_ACCOUNT_PASSWD_RESPONSE MessageType = 1010
)

var MessageType_name = map[int32]string{
	1001: "CREATE_ACCOUNT_REQUEST",
	1002: "CREATE_ACCOUNT_RESPONSE",
	1003: "DELETE_ACCOUNT_REQUEST",
	1004: "DELETE_ACCOUNT_RESPONSE",
	1005: "GET_ACCOUNT_INFO_REQUEST",
	1006: "GET_ACCOUNT_INFO_RESPONSE",
	1007: "SET_ACCOUNT_NAME_REQUEST",
	1008: "SET_ACCOUNT_NAME_RESPONSE",
	1009: "SET_ACCOUNT_PASSWD_REQUEST",
	1010: "SET_ACCOUNT_PASSWD_RESPONSE",
}
var MessageType_value = map[string]int32{
	"CREATE_ACCOUNT_REQUEST":      1001,
	"CREATE_ACCOUNT_RESPONSE":     1002,
	"DELETE_ACCOUNT_REQUEST":      1003,
	"DELETE_ACCOUNT_RESPONSE":     1004,
	"GET_ACCOUNT_INFO_REQUEST":    1005,
	"GET_ACCOUNT_INFO_RESPONSE":   1006,
	"SET_ACCOUNT_NAME_REQUEST":    1007,
	"SET_ACCOUNT_NAME_RESPONSE":   1008,
	"SET_ACCOUNT_PASSWD_REQUEST":  1009,
	"SET_ACCOUNT_PASSWD_RESPONSE": 1010,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Account struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Set              *uint32 `protobuf:"varint,2,req,name=set" json:"set,omitempty"`
	Email            *string `protobuf:"bytes,3,req,name=email" json:"email,omitempty"`
	Name             *string `protobuf:"bytes,4,req,name=name" json:"name,omitempty"`
	Passwd           *string `protobuf:"bytes,5,req,name=passwd" json:"passwd,omitempty"`
	Phone            *string `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Account) GetSet() uint32 {
	if m != nil && m.Set != nil {
		return *m.Set
	}
	return 0
}

func (m *Account) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Account) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *Account) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

type CreateAccountRequest struct {
	Email            *string `protobuf:"bytes,1,req,name=email" json:"email,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Passwd           *string `protobuf:"bytes,3,opt,name=passwd" json:"passwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateAccountRequest) Reset()                    { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()               {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateAccountRequest) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

type CreateAccountResponse struct {
	Rc               *rpc.ResponseCode `protobuf:"bytes,1,req,name=rc" json:"rc,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *CreateAccountResponse) Reset()                    { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()               {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateAccountResponse) GetRc() *rpc.ResponseCode {
	if m != nil {
		return m.Rc
	}
	return nil
}

type DeleteAccountRequest struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteAccountRequest) Reset()                    { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()               {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteAccountRequest) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type DeleteAccountResponse struct {
	Rc               *rpc.ResponseCode `protobuf:"bytes,1,req,name=rc" json:"rc,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DeleteAccountResponse) Reset()                    { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()               {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteAccountResponse) GetRc() *rpc.ResponseCode {
	if m != nil {
		return m.Rc
	}
	return nil
}

type GetAccountInfoRequest struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetAccountInfoRequest) Reset()                    { *m = GetAccountInfoRequest{} }
func (m *GetAccountInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAccountInfoRequest) ProtoMessage()               {}
func (*GetAccountInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetAccountInfoRequest) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type GetAccountInfoResponse struct {
	Rc               *rpc.ResponseCode `protobuf:"bytes,1,req,name=rc" json:"rc,omitempty"`
	Info             *Account          `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetAccountInfoResponse) Reset()                    { *m = GetAccountInfoResponse{} }
func (m *GetAccountInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAccountInfoResponse) ProtoMessage()               {}
func (*GetAccountInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetAccountInfoResponse) GetRc() *rpc.ResponseCode {
	if m != nil {
		return m.Rc
	}
	return nil
}

func (m *GetAccountInfoResponse) GetInfo() *Account {
	if m != nil {
		return m.Info
	}
	return nil
}

type SetAccountNameRequest struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	OldName          *string `protobuf:"bytes,2,req,name=old_name" json:"old_name,omitempty"`
	NewName          *string `protobuf:"bytes,3,req,name=new_name" json:"new_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetAccountNameRequest) Reset()                    { *m = SetAccountNameRequest{} }
func (m *SetAccountNameRequest) String() string            { return proto.CompactTextString(m) }
func (*SetAccountNameRequest) ProtoMessage()               {}
func (*SetAccountNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SetAccountNameRequest) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SetAccountNameRequest) GetOldName() string {
	if m != nil && m.OldName != nil {
		return *m.OldName
	}
	return ""
}

func (m *SetAccountNameRequest) GetNewName() string {
	if m != nil && m.NewName != nil {
		return *m.NewName
	}
	return ""
}

type SetAccountNameResponse struct {
	Rc               *rpc.ResponseCode `protobuf:"bytes,1,req,name=rc" json:"rc,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *SetAccountNameResponse) Reset()                    { *m = SetAccountNameResponse{} }
func (m *SetAccountNameResponse) String() string            { return proto.CompactTextString(m) }
func (*SetAccountNameResponse) ProtoMessage()               {}
func (*SetAccountNameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SetAccountNameResponse) GetRc() *rpc.ResponseCode {
	if m != nil {
		return m.Rc
	}
	return nil
}

type SetAccountPasswdRequest struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetAccountPasswdRequest) Reset()                    { *m = SetAccountPasswdRequest{} }
func (m *SetAccountPasswdRequest) String() string            { return proto.CompactTextString(m) }
func (*SetAccountPasswdRequest) ProtoMessage()               {}
func (*SetAccountPasswdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SetAccountPasswdRequest) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type SetAccountPasswdResponse struct {
	Rc               *rpc.ResponseCode `protobuf:"bytes,1,req,name=rc" json:"rc,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *SetAccountPasswdResponse) Reset()                    { *m = SetAccountPasswdResponse{} }
func (m *SetAccountPasswdResponse) String() string            { return proto.CompactTextString(m) }
func (*SetAccountPasswdResponse) ProtoMessage()               {}
func (*SetAccountPasswdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SetAccountPasswdResponse) GetRc() *rpc.ResponseCode {
	if m != nil {
		return m.Rc
	}
	return nil
}

var E_CreateAccountRequest = &proto.ExtensionDesc{
	ExtendedType:  (*rpc.Body)(nil),
	ExtensionType: (*CreateAccountRequest)(nil),
	Field:         1001,
	Name:          "rpc.account.create_account_request",
	Tag:           "bytes,1001,opt,name=create_account_request",
	Filename:      "account.proto",
}

var E_CreateAccountResponse = &proto.ExtensionDesc{
	ExtendedType:  (*rpc.Body)(nil),
	ExtensionType: (*CreateAccountResponse)(nil),
	Field:         1002,
	Name:          "rpc.account.create_account_response",
	Tag:           "bytes,1002,opt,name=create_account_response",
	Filename:      "account.proto",
}

var E_DeleteAccountRequest = &proto.ExtensionDesc{
	ExtendedType:  (*rpc.Body)(nil),
	ExtensionType: (*DeleteAccountRequest)(nil),
	Field:         1003,
	Name:          "rpc.account.delete_account_request",
	Tag:           "bytes,1003,opt,name=delete_account_request",
	Filename:      "account.proto",
}

var E_DeleteAccountResponse = &proto.ExtensionDesc{
	ExtendedType:  (*rpc.Body)(nil),
	ExtensionType: (*DeleteAccountResponse)(nil),
	Field:         1004,
	Name:          "rpc.account.delete_account_response",
	Tag:           "bytes,1004,opt,name=delete_account_response",
	Filename:      "account.proto",
}

var E_GetAccountInfoRequest = &proto.ExtensionDesc{
	ExtendedType:  (*rpc.Body)(nil),
	ExtensionType: (*GetAccountInfoRequest)(nil),
	Field:         1005,
	Name:          "rpc.account.get_account_info_request",
	Tag:           "bytes,1005,opt,name=get_account_info_request",
	Filename:      "account.proto",
}

var E_GetAccountInfoResponse = &proto.ExtensionDesc{
	ExtendedType:  (*rpc.Body)(nil),
	ExtensionType: (*GetAccountInfoResponse)(nil),
	Field:         1006,
	Name:          "rpc.account.get_account_info_response",
	Tag:           "bytes,1006,opt,name=get_account_info_response",
	Filename:      "account.proto",
}

var E_SetAccountNameRequest = &proto.ExtensionDesc{
	ExtendedType:  (*rpc.Body)(nil),
	ExtensionType: (*SetAccountNameRequest)(nil),
	Field:         1007,
	Name:          "rpc.account.set_account_name_request",
	Tag:           "bytes,1007,opt,name=set_account_name_request",
	Filename:      "account.proto",
}

var E_SetAccountNameResponse = &proto.ExtensionDesc{
	ExtendedType:  (*rpc.Body)(nil),
	ExtensionType: (*SetAccountNameResponse)(nil),
	Field:         1008,
	Name:          "rpc.account.set_account_name_response",
	Tag:           "bytes,1008,opt,name=set_account_name_response",
	Filename:      "account.proto",
}

var E_SetAccountPasswdResquest = &proto.ExtensionDesc{
	ExtendedType:  (*rpc.Body)(nil),
	ExtensionType: (*SetAccountPasswdRequest)(nil),
	Field:         1009,
	Name:          "rpc.account.set_account_passwd_resquest",
	Tag:           "bytes,1009,opt,name=set_account_passwd_resquest",
	Filename:      "account.proto",
}

var E_SetAccountPasswdResponse = &proto.ExtensionDesc{
	ExtendedType:  (*rpc.Body)(nil),
	ExtensionType: (*SetAccountPasswdResponse)(nil),
	Field:         1010,
	Name:          "rpc.account.set_account_passwd_response",
	Tag:           "bytes,1010,opt,name=set_account_passwd_response",
	Filename:      "account.proto",
}

func init() {
	proto.RegisterType((*Account)(nil), "rpc.account.Account")
	proto.RegisterType((*CreateAccountRequest)(nil), "rpc.account.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "rpc.account.CreateAccountResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "rpc.account.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "rpc.account.DeleteAccountResponse")
	proto.RegisterType((*GetAccountInfoRequest)(nil), "rpc.account.GetAccountInfoRequest")
	proto.RegisterType((*GetAccountInfoResponse)(nil), "rpc.account.GetAccountInfoResponse")
	proto.RegisterType((*SetAccountNameRequest)(nil), "rpc.account.SetAccountNameRequest")
	proto.RegisterType((*SetAccountNameResponse)(nil), "rpc.account.SetAccountNameResponse")
	proto.RegisterType((*SetAccountPasswdRequest)(nil), "rpc.account.SetAccountPasswdRequest")
	proto.RegisterType((*SetAccountPasswdResponse)(nil), "rpc.account.SetAccountPasswdResponse")
	proto.RegisterEnum("rpc.account.MessageType", MessageType_name, MessageType_value)
	proto.RegisterExtension(E_CreateAccountRequest)
	proto.RegisterExtension(E_CreateAccountResponse)
	proto.RegisterExtension(E_DeleteAccountRequest)
	proto.RegisterExtension(E_DeleteAccountResponse)
	proto.RegisterExtension(E_GetAccountInfoRequest)
	proto.RegisterExtension(E_GetAccountInfoResponse)
	proto.RegisterExtension(E_SetAccountNameRequest)
	proto.RegisterExtension(E_SetAccountNameResponse)
	proto.RegisterExtension(E_SetAccountPasswdResquest)
	proto.RegisterExtension(E_SetAccountPasswdResponse)
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x5b, 0x6f, 0xda, 0x30,
	0x14, 0xc7, 0x45, 0x80, 0xa6, 0x1c, 0xc6, 0xc4, 0x2c, 0x2e, 0x69, 0x59, 0x37, 0x96, 0xae, 0x12,
	0xda, 0x03, 0x0f, 0x7d, 0xd8, 0xb4, 0xbc, 0xb1, 0x90, 0xa1, 0x4a, 0xe3, 0x32, 0x02, 0xdb, 0xc3,
	0xa4, 0xa1, 0x88, 0xb8, 0x1d, 0x12, 0x24, 0x19, 0x49, 0x55, 0xf5, 0xfb, 0xed, 0xcb, 0xf4, 0x7e,
	0xf9, 0x04, 0x93, 0x1d, 0x2f, 0x04, 0xec, 0x32, 0x1e, 0xed, 0xe3, 0xff, 0xcf, 0x7f, 0x9f, 0xe3,
	0x73, 0x20, 0x67, 0x8d, 0xc7, 0xee, 0xa9, 0x13, 0xd4, 0xbd, 0xb9, 0x1b, 0xb8, 0x28, 0x3b, 0xf7,
	0xc6, 0x75, 0xb6, 0xb5, 0x9b, 0x21, 0x0b, 0xba, 0xaf, 0xfe, 0x04, 0xb9, 0x11, 0xee, 0x22, 0x00,
	0x69, 0x62, 0x2b, 0x89, 0xaa, 0x54, 0xcb, 0xa1, 0x2c, 0x24, 0x7d, 0x1c, 0x28, 0x12, 0x5d, 0xe4,
	0x20, 0x8d, 0x67, 0xd6, 0x64, 0xaa, 0x24, 0xab, 0x52, 0x2d, 0x83, 0x9e, 0x41, 0xca, 0xb1, 0x66,
	0x58, 0x49, 0xd1, 0xd5, 0x73, 0xd8, 0xf2, 0x2c, 0xdf, 0x3f, 0xb3, 0x95, 0x34, 0x5d, 0xe7, 0x20,
	0xed, 0xfd, 0x72, 0x1d, 0xac, 0x6c, 0x55, 0x13, 0xb5, 0x8c, 0xaa, 0x43, 0x41, 0x9f, 0x63, 0x2b,
	0xc0, 0xec, 0x96, 0x3e, 0xfe, 0x7d, 0x8a, 0xfd, 0x60, 0xc1, 0x4c, 0x2c, 0x31, 0x25, 0x22, 0x8a,
	0x31, 0x93, 0x14, 0xf2, 0x1e, 0x8a, 0x2b, 0x10, 0xdf, 0x73, 0x1d, 0x1f, 0xa3, 0x3d, 0x90, 0xe6,
	0x63, 0x8a, 0xc8, 0x1e, 0xbe, 0xa8, 0x93, 0x57, 0xfd, 0x0b, 0xe9, 0xae, 0x8d, 0x55, 0x15, 0x0a,
	0x4d, 0x3c, 0xc5, 0xdc, 0xe5, 0xb1, 0x97, 0x12, 0xf6, 0xca, 0x99, 0xcd, 0xd8, 0xfb, 0x50, 0x6c,
	0xe1, 0x80, 0x89, 0x8e, 0x9c, 0x63, 0x57, 0x04, 0xff, 0x01, 0xa5, 0xd5, 0x43, 0x1b, 0xd1, 0x91,
	0x0a, 0xa9, 0x89, 0x73, 0xec, 0xd2, 0x7c, 0x64, 0x0f, 0x0b, 0xf5, 0x58, 0xf5, 0xea, 0x0c, 0xa7,
	0xb6, 0xa0, 0x68, 0x46, 0xf0, 0x8e, 0x35, 0xc3, 0x02, 0x07, 0x28, 0x0f, 0xdb, 0xee, 0xd4, 0x1e,
	0xb1, 0xe4, 0x92, 0x54, 0xe7, 0x61, 0xdb, 0xc1, 0x67, 0xe1, 0x0e, 0x2d, 0xa8, 0xfa, 0x01, 0x4a,
	0xab, 0xa0, 0xcd, 0x72, 0x70, 0x00, 0xe5, 0x85, 0xb0, 0x47, 0x2b, 0x26, 0xca, 0xc2, 0x47, 0x50,
	0xf8, 0x63, 0x1b, 0xdd, 0xf0, 0xee, 0x8f, 0x04, 0xd9, 0x36, 0xf6, 0x7d, 0xeb, 0x04, 0x0f, 0xce,
	0x3d, 0x8c, 0x2a, 0x50, 0xd2, 0xfb, 0x46, 0x63, 0x60, 0x8c, 0x1a, 0xba, 0xde, 0x1d, 0x76, 0x06,
	0xa3, 0xbe, 0xf1, 0x75, 0x68, 0x98, 0x83, 0xfc, 0x85, 0x8c, 0x5e, 0x42, 0x99, 0x0b, 0x9a, 0xbd,
	0x6e, 0xc7, 0x34, 0xf2, 0x97, 0x32, 0x91, 0x36, 0x8d, 0x2f, 0x86, 0x40, 0x7a, 0x45, 0xa5, 0x5c,
	0x90, 0x49, 0xaf, 0x65, 0xb4, 0x07, 0x4a, 0xcb, 0x18, 0x44, 0xa1, 0xa3, 0xce, 0xe7, 0x6e, 0x24,
	0xbe, 0x91, 0xd1, 0x2b, 0xd8, 0x11, 0x84, 0x99, 0xfc, 0x96, 0xca, 0xcd, 0x58, 0xbc, 0xd3, 0x68,
	0x1b, 0x91, 0xfc, 0x8e, 0xca, 0x05, 0x61, 0x26, 0xbf, 0x97, 0xd1, 0x6b, 0xd8, 0x8d, 0xc7, 0x7b,
	0x0d, 0xd3, 0xfc, 0xde, 0x8c, 0x00, 0x0f, 0x32, 0xaa, 0x42, 0x45, 0x78, 0x80, 0x21, 0x1e, 0x65,
	0xad, 0x0d, 0xa5, 0x31, 0x6d, 0xa0, 0x11, 0xfb, 0x44, 0xa3, 0x39, 0xab, 0x53, 0x86, 0xe6, 0xfc,
	0x93, 0x6b, 0x9f, 0x2b, 0x17, 0x32, 0xfd, 0x6c, 0x6f, 0x96, 0x3e, 0x9b, 0xa8, 0x79, 0xb5, 0x2e,
	0x94, 0x39, 0x1c, 0xab, 0x67, 0x8c, 0x77, 0x19, 0xf2, 0xd4, 0x75, 0xbc, 0x50, 0x45, 0xfc, 0xd9,
	0xb4, 0x09, 0xd7, 0xf9, 0xbb, 0x12, 0xf9, 0x13, 0xf5, 0x37, 0xf1, 0xc7, 0xe1, 0x78, 0x7f, 0xd7,
	0x22, 0x7f, 0xc2, 0x59, 0xa0, 0xf5, 0x40, 0x39, 0xc1, 0x41, 0x44, 0x23, 0xad, 0x29, 0x72, 0x78,
	0x23, 0x22, 0x0a, 0xa7, 0x84, 0xd6, 0x87, 0x1d, 0x01, 0x91, 0x37, 0x79, 0x1b, 0x22, 0xf7, 0xd7,
	0x22, 0x17, 0x2e, 0xfd, 0x18, 0x93, 0x74, 0xb8, 0xc8, 0xe5, 0x9d, 0xc8, 0xa5, 0x70, 0x92, 0x10,
	0x97, 0x02, 0x22, 0xef, 0xf2, 0x5e, 0xe4, 0x52, 0x3c, 0x53, 0xb4, 0x21, 0x54, 0xe2, 0xcc, 0x70,
	0xd0, 0x13, 0x2a, 0x67, 0xf4, 0x21, 0xa4, 0xbe, 0x7d, 0x82, 0xba, 0x34, 0x70, 0xb4, 0x6f, 0x4f,
	0x61, 0x39, 0xb3, 0x8f, 0x21, 0xf6, 0xe0, 0x3f, 0xd8, 0x50, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x4d, 0xae, 0x2d, 0xa6, 0x48, 0x07, 0x00, 0x00,
}
